server:
  port: 10000

spring:
  application:
    name: gateway

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace:
      config:
        import-check:
          enabled: false
    circuitbreaker:
      sentinel:
        enabled: true
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719
      filter:
        enabled: true
      datasource:
        gw-flow:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            data-id: ${spring.application.name}-gw-flow-rules
            group-id: SENTINEL_GROUP
            rule-type: gw-flow
        degrade:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            data-id: ${spring.application.name}-degrade-rules
            group-id: SENTINEL_GROUP
            rule-type: DEGRADE

    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 2s
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - name: StripPrefix
              args:
                parts: 1
            - name: CircuitBreaker
              args:
                name: userServiceCircuitBreaker
                fallbackUri: forward:/fallback/user
        - id: order-service-route
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
          filters:
            - name: StripPrefix
              args:
                parts: 1
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - "*"
            allowed-methods:
              - "*"
            allowed-headers:
              - "*"
            allowCredentials: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,sentinel
  endpoint:
    gateway:
      enabled: true
    health:
      enabled: true
    sentinel:
      enabled: true
